export default {
  vice: [
    {
      name: "Arshia Sharma",
      votes: 0,
      votes_6: 0,
      votes_7: 0,
      votes_8: 0,
      votes_9: 0,
      votes_10: 0,
      votes_11: 0,
      votes_12: 0,
      photo:
        "https://cloud-g3v2r588p-hack-club-bot.vercel.app/0student_council_member_1.jpg",
      slogan: "Keeping everyone accountable.",
      id: 1,
    },
    {
      name: "Arina Evtushenko",
      votes: 0,
      votes_6: 0,
      votes_7: 0,
      votes_8: 0,
      votes_9: 0,
      votes_10: 0,
      votes_11: 0,
      votes_12: 0,
      photo:
        "https://cloud-g3v2r588p-hack-club-bot.vercel.app/0student_council_member_1.jpg",
      slogan: "Keeping everyone accountable.",
      id: 4,
    },
  ],
  president: [
    {
      name: "Edwin Cheah",
      votes: 0,
      votes_6: 0,
      votes_7: 0,
      votes_8: 0,
      votes_9: 0,
      votes_10: 0,
      votes_11: 0,
      votes_12: 0,
      photo:
        "https://cloud-rey4jozc0-hack-club-bot.vercel.app/0student_council_member_6.jpg",
      slogan: "Keeping everyone accountable.",
      id: 1,
    },
    {
      name: "Tony Shi",
      votes: 0,
      votes_6: 0,
      votes_7: 0,
      votes_8: 0,
      votes_9: 0,
      votes_10: 0,
      votes_11: 0,
      votes_12: 0,
      photo:
        "https://cloud-g3v2r588p-hack-club-bot.vercel.app/1student_council_member_6.jpg",
      slogan: "Keeping everyone accountable.",
      id: 2,
    },
  ],
};
